### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Shikkic** [Devatoria/go-graylog#1]
Hey! I wanted to try using out this library but noticed there was no explicit license for the repo. Would you mind adding one so I can be sure there would be no legal conflict with using this library.

Thanks!

**Comment by Devatoria** [comment]
Hi, thank you for the notice :) I just forgot it... I added an MIT license.
Hope it's ok for you.

2017-10-23 17:00 GMT+02:00 Dan Cadden <notifications@github.com>:

**Comment by Shikkic** [comment]
Thanks for the fast reply, much appreciated!

**Comment by Shikkic** [comment]
Opps, I closed the issue by accident. I will close the issue once the license is in the repo, thanks.

**Comment by Devatoria** [comment]
It should be done ;)

**Comment by Shikkic** [comment]
Hm, I still don't see it in the repo as a `LICENSE` file?

![Imgur](https://i.imgur.com/rRVZcdr.png)

**Comment by Devatoria** [comment]
WELL, since I was replying directly from my email app and not from GitHub, I added the license file to the wrong repository... I'm really sorry 😄 ! Now, it's ok.

**Comment by Shikkic** [comment]
No worries, thanks for taking the time out of your day to help 😄
